### ISSUE TITLE
consider renaming repository

### ISSUE THREAD

**Issue by garu** [CPAN-Security/security.metacpan.org#1]
'security.cpan.org' implies a very specific domain, and while I think security.cpan.org _should_ point to our website, I also think we should just as well serve MetaCPAN (through security.metacpan.org or metacpan.org/security/), and maybe even consider also holding a tld name of our own.

Due to the many possibilities of mirroring the website, I think this repository should be renamed to something more generic, like 'cpansecurity-web' or 'cpan-security-web' or even just 'website' (though that may confuse people cloning the repo.

**Comment by sjn** [comment]
I for one am happy with "security.metacpan.org" containing content for that domain, and "security.cpan.org" containing equivalent for it (currently a browser redirect only).

Maybe "cpansec-web" would be an alternative, though I'm not so sure if such a change can be utilized well as long as we're using github pages to serve content. AFAIK, the `CNAME` file (which is used to specify which hostname the github pages server listens to) only may contain a single hostname, so the repository is in fact in practice only available for one host at a time. :cry:

If I'm wrong about `CNAME` though, or we move away from gh pages, then renaming the repo makes a _lot_ of sense.

With this in mind – what do you think? I'm unsure about renaming it to `cpansec-web` (or whatever), or to postpone it until need to host our own thing.

**Comment by Tux** [comment]
I guess this issue should be closed

**Comment by sjn** [comment]
I'm fine with closing this issue as it is, if @garu is. I guess we can open it again if mirroring becomes an issue?
