### ISSUE TITLE
Lightening talk for oalders@TPRC-in-Toronto

### ISSUE THREAD

**Issue by sjn** [CPAN-Security/security.metacpan.org#14]
@oalders has offered to give a lightening talk about CPAN-SEC at the Perl & Raku conference in Toronto. Make some slides for him! 😁

**Comment by sjn** [comment]
Pretty much done, result can be found here: https://security.metacpan.org/presentations/tprc2023-cpan-sec-lightening-talk/

**Comment by oalders** [comment]
@ingy may want to give this talk, so I'm pinging him here.

**Comment by sjn** [comment]
Done and delivered. No video published yet
