### ISSUE TITLE
merge charter information into Readme.md

### ISSUE THREAD

**Issue by garu** [CPAN-Security/security.metacpan.org#6]
This way, people stumbling on the repo will understand all the basic information without having to actually go to the website.

**Comment by sjn** [comment]
We may want to finish & clean up the charter first though. Also, some of the stuff there is maybe a bit much for a landing page?

**Comment by sjn** [comment]
This is partially related to #21

**Comment by sjn** [comment]
This weekend I added an index.md file, that now is being served as the security.metacpan.org fontpage. This frees up README.md for other things, including sharing some basic information about the group, taken from the charter. :-)
