### ISSUE TITLE
get security.cpan.org to point to the website

### ISSUE THREAD

**Issue by garu** [CPAN-Security/security.metacpan.org#8]

**Comment by sjn** [comment]
@stigtsp has sent a mail to Perl NOC about this! :heart:

**Comment by sjn** [comment]
@stigtsp set up a redir; it'll have to do for now.

**Comment by stigtsp** [comment]
There is already a hacky HTML-redirect set up, waiting for NOC to get back to us.

**Comment by stigtsp** [comment]
Closing this issue for now
